package model

// type USER_ROLE string

// const (
// 	USER_ROLE_OWNER      USER_ROLE = "owner"
// 	USER_ROLE_SUPERADMIN USER_ROLE = "superadmin"
// 	USER_ROLE_CASHIER    USER_ROLE = "cashier"
// 	USER_ROLE_MANAGER    USER_ROLE = "manager"
// )

// type BARCODE_TYPE string

// const (
// 	BARCODE_TYPE_EAN13 BARCODE_TYPE = "ean13"
// 	BARCODE_TYPE_EAN8  BARCODE_TYPE = "ean8"
// 	BARCODE_TYPE_UPC   BARCODE_TYPE = "upc"
// )

// type TRANSACTION_STATUS string

// const (
// 	TRANSACTION_STATUS_PENDING   TRANSACTION_STATUS = "pending"
// 	TRANSACTION_STATUS_PAID      TRANSACTION_STATUS = "paid"
// 	TRANSACTION_STATUS_EXPIRED   TRANSACTION_STATUS = "expired"
// 	TRANSACTION_STATUS_CANCELLED TRANSACTION_STATUS = "cancelled"
// )
